services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000" # Expose frontend on port 3000
    networks:
      - todo-network

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    ports:
      - "4000:4000" # Expose backend on port 4000
    networks:
      - todo-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Expose Nginx on port 80
    networks:
      - todo-network

networks:
  todo-network:
